# Generated by Django 5.0.4 on 2025-06-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="APP.classcategory",
            ),
        ),
    ]
